In [13]:
import torch
import numpy as np
#import pandas as pd

from PatchTST_supervised.layers.EcmP_layers import series_decomp

In [2]:
# idea 1, 2 stages patching

test_input = torch.tensor([[[5,2,3], [123,4,7]]]).float()   #shape (1,2,3)

print(test_input.shape)

# each patch into embedding

d_model = 24
d_patch = 16

w_patch_indv = torch.nn.Linear(test_input.shape[-1], d_patch)

x = w_patch_indv(test_input)

print(x)
print(x.shape)

#flatten channels

x = x.view(test_input.shape[0],-1)

print(x)



# merge each channels into the patches

w_channel_m = torch.nn.Linear(x.shape[-1], d_model)

x = w_channel_m(x)

print(x)
print(x.shape)


torch.Size([1, 2, 3])
tensor([[[ 1.8122e+00,  8.0565e-01, -1.0789e+00, -2.9956e+00, -4.8203e-02,
           2.5044e+00,  2.5577e+00,  2.0470e+00, -8.0749e-03,  1.1986e+00,
           2.2260e-01, -3.1251e+00, -1.5328e-01,  1.9644e+00,  2.2427e+00,
          -2.1394e+00],
         [ 4.8488e+01,  2.6191e+01, -7.1233e+00, -5.4119e+01,  4.9041e+00,
           6.9447e+01,  4.5003e+01, -1.2866e+01,  5.8508e+00,  3.5856e+01,
           3.9250e+01, -2.6906e+01, -5.9834e+01,  1.8614e+01,  6.5809e+01,
          -8.6072e+00]]], grad_fn=<AddBackward0>)
torch.Size([1, 2, 16])
tensor([[ 1.8122e+00,  8.0565e-01, -1.0789e+00, -2.9956e+00, -4.8203e-02,
          2.5044e+00,  2.5577e+00,  2.0470e+00, -8.0749e-03,  1.1986e+00,
          2.2260e-01, -3.1251e+00, -1.5328e-01,  1.9644e+00,  2.2427e+00,
         -2.1394e+00,  4.8488e+01,  2.6191e+01, -7.1233e+00, -5.4119e+01,
          4.9041e+00,  6.9447e+01,  4.5003e+01, -1.2866e+01,  5.8508e+00,
          3.5856e+01,  3.9250e+01, -2.6906e+01, -5.9834e+01, 

In [3]:
torch.cuda.is_available()

True

In [41]:
test_input[:,:,:]

NameError: name 'test_input' is not defined

In [4]:
t1 = torch.tensor([[[5,2]], [[1,8]]])

t2 = torch.tensor([[[1,1]], [[1,1]]])

In [42]:
x1 = torch.rand([2,5,1])

print(x1)

tensor([[[0.2417],
         [0.0367],
         [0.0638],
         [0.1731],
         [0.3667]],

        [[0.2931],
         [0.4409],
         [0.2218],
         [0.3433],
         [0.0513]]])


In [43]:
y1, y2 = s_d(x1)

In [44]:
print(y1)
print(y2)

tensor([[[ 0.0683],
         [-0.0774],
         [-0.0274],
         [-0.0281],
         [ 0.0645]],

        [[-0.0493],
         [ 0.1223],
         [-0.1136],
         [ 0.1379],
         [-0.0974]]])
tensor([[[0.1734],
         [0.1141],
         [0.0912],
         [0.2012],
         [0.3022]],

        [[0.3424],
         [0.3186],
         [0.3353],
         [0.2055],
         [0.1486]]])
