In [2]:
import torch
import numpy as np
#import pandas as pd

In [8]:
# idea 1, 2 stages patching

test_input = torch.tensor([[[5,2,3], [123,4,7]]]).float()   #shape (2,3)

print(test_input.shape)

# each patch into embedding

d_model = 24
d_patch = 16

w_patch_indv = torch.nn.Linear(test_input.shape[-1], d_patch)

x = w_patch_indv(test_input)

print(x)
print(x.shape)

#flatten channels

x = x.view(test_input.shape[0],-1)

print(x)



# merge each channels into the patches

w_channel_m = torch.nn.Linear(x.shape[-1], d_model)

x = w_channel_m(x)

print(x)
print(x.shape)


torch.Size([1, 2, 3])
tensor([[[  1.9975,   0.9039,  -3.9002,   2.1717,  -3.3017,  -1.7104,   2.1665,
           -0.5115,  -3.6455,   0.6912,  -1.2258,   2.8113,  -2.8252,   1.9020,
           -1.0045,  -1.5456],
         [ 61.4037,  41.8897, -70.4480,  41.9692, -61.7969, -54.4200,  62.8324,
          -44.2808, -24.2937,   6.8598,   3.6059,  33.6072, -53.0543,  40.1890,
          -13.3089, -33.8818]]], grad_fn=<AddBackward0>)
torch.Size([1, 2, 16])
tensor([[  1.9975,   0.9039,  -3.9002,   2.1717,  -3.3017,  -1.7104,   2.1665,
          -0.5115,  -3.6455,   0.6912,  -1.2258,   2.8113,  -2.8252,   1.9020,
          -1.0045,  -1.5456,  61.4037,  41.8897, -70.4480,  41.9692, -61.7969,
         -54.4200,  62.8324, -44.2808, -24.2937,   6.8598,   3.6059,  33.6072,
         -53.0543,  40.1890, -13.3089, -33.8818]], grad_fn=<ViewBackward0>)
tensor([[ -8.3447,  13.3558,  14.8459, -11.7567, -14.8710,  35.1665,  13.6365,
         -44.2741,   2.3172,   4.6831, -14.0775,  27.2935, -11.6611, -11.055

In [9]:
torch.cuda.is_available()

True