In [6]:
import torch
import numpy as np
#import pandas as pd

In [7]:
# idea 1, 2 stages patching

test_input = torch.tensor([[[5,2,3], [123,4,7]]]).float()   #shape (1,2,3)

print(test_input.shape)

# each patch into embedding

d_model = 24
d_patch = 16

w_patch_indv = torch.nn.Linear(test_input.shape[-1], d_patch)

x = w_patch_indv(test_input)

print(x)
print(x.shape)

#flatten channels

x = x.view(test_input.shape[0],-1)

print(x)



# merge each channels into the patches

w_channel_m = torch.nn.Linear(x.shape[-1], d_model)

x = w_channel_m(x)

print(x)
print(x.shape)


torch.Size([1, 2, 3])
tensor([[[  0.8644,  -0.9350,   1.9623,  -0.4483,  -1.9400,  -1.7939,  -2.4361,
            2.6278,  -0.7460,  -1.0360,   0.4741,  -0.6072,   2.2550,   1.0718,
           -1.0974,  -1.9452],
         [ 50.1215,   9.4809,  38.6461,  39.9357, -21.8199, -54.0093, -23.6638,
           68.1792, -30.2031, -58.8319,  43.1630, -58.0977,  47.2271,  10.7561,
           10.0499, -63.8197]]], grad_fn=<AddBackward0>)
torch.Size([1, 2, 16])
tensor([[  0.8644,  -0.9350,   1.9623,  -0.4483,  -1.9400,  -1.7939,  -2.4361,
           2.6278,  -0.7460,  -1.0360,   0.4741,  -0.6072,   2.2550,   1.0718,
          -1.0974,  -1.9452,  50.1215,   9.4809,  38.6461,  39.9357, -21.8199,
         -54.0093, -23.6638,  68.1792, -30.2031, -58.8319,  43.1630, -58.0977,
          47.2271,  10.7561,  10.0499, -63.8197]], grad_fn=<ViewBackward0>)
tensor([[-14.5153,  -0.1267,  39.5719,   7.8428,  48.9234,  12.1633,  27.0821,
           8.3776, -31.3476,  14.3631,  19.4341,  -5.6211,  29.1198,   2.319

In [8]:
torch.cuda.is_available()

True

In [9]:
test_input[:,:,:]

tensor([[[  5.,   2.,   3.],
         [123.,   4.,   7.]]])