In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
# idea 1, 2 stages patching

test_input = torch.tensor([[5,2,3], [123,4,7]]).float()   #shape (2,3)

print(test_input.shape)

# each patch into embedding

d_model = 32
d_patch = 16

w_patch_indv = torch.nn.Linear(test_input.shape[1], d_patch)

x = w_patch_indv(test_input)

print(x)
print(x.shape)

#flatten channels

x = x.view(-1)

print(x)



# merge each channels into the patches

w_channel_m = torch.nn.Linear(x.shape[0], d_model)

x = w_channel_m(x)

print(x)
print(x.shape)


torch.Size([2, 3])
tensor([[  4.6257,  -1.6788,   0.6811,  -1.2430,  -3.0429,  -1.4799,   1.8272,
           0.3229,  -0.6663,   1.9405,   3.2772,   3.7112,  -2.3815,   1.5453,
          -0.2690,  -3.1102],
        [ 65.2144, -59.3474,  15.1797, -52.5843, -25.5713, -50.0275,  49.5692,
          45.9517,   8.1941,  24.4910,  63.1394,  61.5667, -41.0966,  -2.5194,
         -61.3413, -19.2633]], grad_fn=<AddmmBackward0>)
torch.Size([2, 16])
tensor([  4.6257,  -1.6788,   0.6811,  -1.2430,  -3.0429,  -1.4799,   1.8272,
          0.3229,  -0.6663,   1.9405,   3.2772,   3.7112,  -2.3815,   1.5453,
         -0.2690,  -3.1102,  65.2144, -59.3474,  15.1797, -52.5843, -25.5713,
        -50.0275,  49.5692,  45.9517,   8.1941,  24.4910,  63.1394,  61.5667,
        -41.0966,  -2.5194, -61.3413, -19.2633], grad_fn=<ViewBackward0>)
tensor([ 12.0544, -17.0241,  -1.4515,  -7.6158,  20.6663,  24.7793, -11.2734,
         -6.9495, -20.3165,  22.7216,  -8.7802, -12.1654, -20.6531, -14.2307,
         18.3421

In [3]:
torch.cuda.is_available()

True