In [1]:
import torch
import numpy as np
#import pandas as pd

In [2]:
# idea 1, 2 stages patching

test_input = torch.tensor([[[5,2,3], [123,4,7]]]).float()   #shape (2,3)

print(test_input.shape)

# each patch into embedding

d_model = 24
d_patch = 16

w_patch_indv = torch.nn.Linear(test_input.shape[-1], d_patch)

x = w_patch_indv(test_input)

print(x)
print(x.shape)

#flatten channels

x = x.view(test_input.shape[0],-1)

print(x)



# merge each channels into the patches

w_channel_m = torch.nn.Linear(x.shape[-1], d_model)

x = w_channel_m(x)

print(x)
print(x.shape)


torch.Size([1, 2, 3])
tensor([[[  2.9040,   1.5302,  -2.7371,  -2.7148,  -1.6294,  -1.0592,  -3.5222,
           -0.3397,   0.9935,  -2.4107,  -1.4018,  -0.4002,   0.8688,  -0.9846,
            1.2634,   2.8140],
         [ 34.5277,   8.8665, -45.2440, -61.0241,  12.9069, -65.4946, -54.6975,
          -45.7423,  26.0041, -53.3968,   2.2561, -31.3069,  -9.1893, -61.5312,
           51.0009,  65.3407]]], grad_fn=<AddBackward0>)
torch.Size([1, 2, 16])
tensor([[  2.9040,   1.5302,  -2.7371,  -2.7148,  -1.6294,  -1.0592,  -3.5222,
          -0.3397,   0.9935,  -2.4107,  -1.4018,  -0.4002,   0.8688,  -0.9846,
           1.2634,   2.8140,  34.5277,   8.8665, -45.2440, -61.0241,  12.9069,
         -65.4946, -54.6975, -45.7423,  26.0041, -53.3968,   2.2561, -31.3069,
          -9.1893, -61.5312,  51.0009,  65.3407]], grad_fn=<ViewBackward0>)
tensor([[-45.1112,  -9.5030,  14.2948, -26.5046,  -7.6946,  -1.6786,   6.1004,
           9.8166,   1.4149,  24.5514,  -2.7491,  32.6801,   2.7385,  10.438

In [3]:
torch.cuda.is_available()

True

In [5]:
test_input[:,:,:]

tensor([[[  5.,   2.,   3.],
         [123.,   4.,   7.]]])