In [1]:
import torch
import numpy as np
#import pandas as pd

from EcmP_supervised.layers.EcmP_layers import series_decomp

c:\Users\Vincent\.conda\envs\Pytorch_1_11\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
# idea 1, 2 stages patching

test_input = torch.tensor([[[5,2,3], [123,4,7]]]).float()   #shape (1,2,3)

print(test_input.shape)

# each patch into embedding

d_model = 24
d_patch = 16

w_patch_indv = torch.nn.Linear(test_input.shape[-1], d_patch)

x = w_patch_indv(test_input)

print(x)
print(x.shape)

#flatten channels

x = x.view(test_input.shape[0],-1)

print(x.shape)



# merge each channels into the patches

w_channel_m = torch.nn.Linear(x.shape[-1], d_model)

x = w_channel_m(x)

print(x)
print(x.shape[1])


torch.Size([1, 2, 3])
tensor([[[  0.8136,   1.1169,   0.3454,  -2.2691,   1.4340,   2.2030,  -4.3210,
           -1.4900,   0.3377,   3.3877,  -4.1011,  -2.7281,   1.9255,   1.6201,
           -3.6247,  -1.9479],
         [ 63.7521,  38.7186, -28.1333, -62.2381,  22.3293,   0.2731, -60.4720,
           -2.5868,   4.4808,  63.2928, -67.1241, -25.4295,  16.7008,  66.2117,
          -59.7428, -60.1647]]], grad_fn=<AddBackward0>)
torch.Size([1, 2, 16])
torch.Size([1, 32])
tensor([[ 20.2115,   3.0888,   1.0161,  51.9251,  -9.8811,  14.5502,  -3.2287,
         -13.1822,  36.2783,  21.5806,   4.8223,  24.2714, -21.6600,  -0.6491,
         -12.3721,   8.5407,  34.7497,  24.1908,   8.9852, -26.6065,   6.9476,
          21.4202, -12.6643, -19.5497]], grad_fn=<AddmmBackward0>)
24


In [3]:
torch.cuda.is_available()

True

In [5]:
test_input[:,:,:]

tensor([[[  5.,   2.,   3.],
         [123.,   4.,   7.]]])

In [13]:
t1 = torch.tensor([[[5,2]], [[1,8]]])

t2 = torch.tensor([[[1,1]], [[1,-10]]])

print(t1)

print(t2)

print(t1.shape, t2.shape)

tensor([[[5, 2]],

        [[1, 8]]])
tensor([[[  1,   1]],

        [[  1, -10]]])
torch.Size([2, 1, 2]) torch.Size([2, 1, 2])


In [14]:
t3 = t1 + t2

print(t3)
print(t3.shape)

tensor([[[ 6,  3]],

        [[ 2, -2]]])
torch.Size([2, 1, 2])


In [8]:
y1, y2 = s_d(x1)

NameError: name 's_d' is not defined

In [ ]:
print(y1)
print(y2)

tensor([[[ 0.0683],
         [-0.0774],
         [-0.0274],
         [-0.0281],
         [ 0.0645]],

        [[-0.0493],
         [ 0.1223],
         [-0.1136],
         [ 0.1379],
         [-0.0974]]])
tensor([[[0.1734],
         [0.1141],
         [0.0912],
         [0.2012],
         [0.3022]],

        [[0.3424],
         [0.3186],
         [0.3353],
         [0.2055],
         [0.1486]]])
