In [1]:
import torch
import numpy as np
import pandas as pd

c:\Users\Vincent\.conda\envs\Pytorch_1_11\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
# idea 1, 2 stages patching

test_input = torch.tensor([[5,2,3], [123,4,7]]).float()   #shape (2,3)

print(test_input.shape)

# each patch into embedding

d_model = 32
d_patch = 16

w_patch_indv = torch.nn.Linear(test_input.shape[1], d_patch)

x = w_patch_indv(test_input)

print(x)
print(x.shape)

#flatten channels

x = x.view(-1)

print(x)



# merge each channels into the patches

w_channel_m = torch.nn.Linear(x.shape[0], d_model)

x = w_channel_m(x)

print(x)
print(x.shape)


torch.Size([2, 3])
tensor([[ -2.6748,   0.5606,   1.2652,  -0.9978,  -1.4814,   1.5100,   2.0574,
          -2.5919,  -0.2793,   1.4982,  -0.9771,   1.2393,  -0.9900,   1.5096,
           0.7221,  -0.6882],
        [-43.7282, -14.6149,  18.0454,   8.0633, -33.6273,  -5.8366,  22.4371,
         -24.5000, -17.1731, -18.7164,   0.8406,  38.3874, -54.6885,  54.2884,
          60.5586,   8.0550]], grad_fn=<AddmmBackward0>)
torch.Size([2, 16])
tensor([ -2.6748,   0.5606,   1.2652,  -0.9978,  -1.4814,   1.5100,   2.0574,
         -2.5919,  -0.2793,   1.4982,  -0.9771,   1.2393,  -0.9900,   1.5096,
          0.7221,  -0.6882, -43.7282, -14.6149,  18.0454,   8.0633, -33.6273,
         -5.8366,  22.4371, -24.5000, -17.1731, -18.7164,   0.8406,  38.3874,
        -54.6885,  54.2884,  60.5586,   8.0550], grad_fn=<ViewBackward0>)
tensor([-14.5223, -18.8572,  -0.3522,   8.3283, -12.0920,   1.3381,   4.4405,
          0.0649, -14.5960,   1.0177,   8.3950,  16.8855,  -0.3171,   0.1681,
         13.6840