In [2]:
import torch
import numpy as np
#import pandas as pd

from EcmP_supervised.layers.EcmP_layers import series_decomp

In [3]:
# idea 1, 2 stages patching

test_input = torch.tensor([[[5,2,3], [123,4,7]]]).float()   #shape (1,2,3)

print(test_input.shape)

# each patch into embedding

d_model = 24
d_patch = 16

w_patch_indv = torch.nn.Linear(test_input.shape[-1], d_patch)

x = w_patch_indv(test_input)

print(x)
print(x.shape)

#flatten channels

x = x.view(test_input.shape[0],-1)

print(x.shape)



# merge each channels into the patches

w_channel_m = torch.nn.Linear(x.shape[-1], d_model)

x = w_channel_m(x)

print(x)
print(x.shape)


torch.Size([1, 2, 3])
tensor([[[-4.4311e+00,  3.4409e-01,  1.9307e+00, -1.0115e+00, -1.9602e-01,
          -1.5067e+00,  7.0424e-01, -8.2680e-01,  3.2022e+00,  3.2146e+00,
           2.5586e+00, -2.8903e+00,  2.6180e-01,  3.0770e+00,  6.2029e-02,
          -1.3673e+00],
         [-6.4032e+01,  4.4100e+01,  3.3211e+01, -3.2573e+01, -1.7967e+01,
          -4.8011e+01, -3.8599e+00, -2.1378e+01,  5.4975e+01,  3.6758e+01,
           5.8617e+01, -1.8548e+01, -4.8269e+00,  4.8751e+01, -3.4251e+01,
          -4.1559e+00]]], grad_fn=<AddBackward0>)
torch.Size([1, 2, 16])
torch.Size([1, 32])
tensor([[ 38.5087, -12.9167, -16.1899,   4.5754, -16.6418,  10.5746,   6.0573,
         -29.7502, -20.0779, -17.5315,  24.4538,  -1.7213, -13.9729,   9.5615,
          -1.0221, -16.2994,  27.6938, -19.2946, -25.1626,   4.8231,   3.7002,
          -4.6443,  15.7647,  -2.9792]], grad_fn=<AddmmBackward0>)
torch.Size([1, 24])


In [4]:
torch.cuda.is_available()

True

In [5]:
test_input[:,:,:]

tensor([[[  5.,   2.,   3.],
         [123.,   4.,   7.]]])

In [6]:
t1 = torch.tensor([[[5,2]], [[1,8]]])

t2 = torch.tensor([[[1,1]], [[1,1]]])

In [7]:
x1 = torch.rand([2,5,1])

print(x1)

tensor([[[0.2699],
         [0.0483],
         [0.8931],
         [0.8853],
         [0.2695]],

        [[0.4461],
         [0.9978],
         [0.7728],
         [0.1371],
         [0.8768]]])


In [8]:
y1, y2 = s_d(x1)

NameError: name 's_d' is not defined

In [ ]:
print(y1)
print(y2)

tensor([[[ 0.0683],
         [-0.0774],
         [-0.0274],
         [-0.0281],
         [ 0.0645]],

        [[-0.0493],
         [ 0.1223],
         [-0.1136],
         [ 0.1379],
         [-0.0974]]])
tensor([[[0.1734],
         [0.1141],
         [0.0912],
         [0.2012],
         [0.3022]],

        [[0.3424],
         [0.3186],
         [0.3353],
         [0.2055],
         [0.1486]]])
