In [1]:
import torch
import numpy as np
#import pandas as pd

In [2]:
# idea 1, 2 stages patching

test_input = torch.tensor([[[5,2,3], [123,4,7]]]).float()   #shape (1,2,3)

print(test_input.shape)

# each patch into embedding

d_model = 24
d_patch = 16

w_patch_indv = torch.nn.Linear(test_input.shape[-1], d_patch)

x = w_patch_indv(test_input)

print(x)
print(x.shape)

#flatten channels

x = x.view(test_input.shape[0],-1)

print(x)



# merge each channels into the patches

w_channel_m = torch.nn.Linear(x.shape[-1], d_model)

x = w_channel_m(x)

print(x)
print(x.shape)


torch.Size([1, 2, 3])
tensor([[[ 1.8122e+00,  8.0565e-01, -1.0789e+00, -2.9956e+00, -4.8203e-02,
           2.5044e+00,  2.5577e+00,  2.0470e+00, -8.0749e-03,  1.1986e+00,
           2.2260e-01, -3.1251e+00, -1.5328e-01,  1.9644e+00,  2.2427e+00,
          -2.1394e+00],
         [ 4.8488e+01,  2.6191e+01, -7.1233e+00, -5.4119e+01,  4.9041e+00,
           6.9447e+01,  4.5003e+01, -1.2866e+01,  5.8508e+00,  3.5856e+01,
           3.9250e+01, -2.6906e+01, -5.9834e+01,  1.8614e+01,  6.5809e+01,
          -8.6072e+00]]], grad_fn=<AddBackward0>)
torch.Size([1, 2, 16])
tensor([[ 1.8122e+00,  8.0565e-01, -1.0789e+00, -2.9956e+00, -4.8203e-02,
          2.5044e+00,  2.5577e+00,  2.0470e+00, -8.0749e-03,  1.1986e+00,
          2.2260e-01, -3.1251e+00, -1.5328e-01,  1.9644e+00,  2.2427e+00,
         -2.1394e+00,  4.8488e+01,  2.6191e+01, -7.1233e+00, -5.4119e+01,
          4.9041e+00,  6.9447e+01,  4.5003e+01, -1.2866e+01,  5.8508e+00,
          3.5856e+01,  3.9250e+01, -2.6906e+01, -5.9834e+01, 

In [3]:
torch.cuda.is_available()

True

In [4]:
test_input[:,:,:]

tensor([[[  5.,   2.,   3.],
         [123.,   4.,   7.]]])